theme: jekyll-theme-minimal
title: No Journey Recipes
description: Simple recepies to remind me how to make things my family like, without having to look up ad-infested recepies online.  No heart-warming AI generated stories about my Grandma's cooking for the benfit of SEO.

