theme: jekyll-theme-minimal
title: No Journey Recipes
description: Simple recepies to remind me how to make what my family like, without having to look up ad-infested recepies online.  No LLM-generated stories about my Grandma's cooking for SEO.

